"""empty message

Revision ID: 33174ec74397
Revises: 58320d313b90
Create Date: 2024-10-21 12:38:46.825668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33174ec74397'
down_revision = '58320d313b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bs_table_company_cik_companies_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bs_table_company_cik_companies_table'), 'companies_table', ['company_cik'], ['cik'])

    with op.batch_alter_table('cf_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cf_table_company_cik_companies_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cf_table_company_cik_companies_table'), 'companies_table', ['company_cik'], ['cik'])

    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inc_table_company_cik_companies_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inc_table_company_cik_companies_table'), 'companies_table', ['company_cik'], ['cik'])

    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t', sa.String(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('t')

    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inc_table_company_cik_companies_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_inc_table_company_cik_companies_table', 'companies_table', ['company_cik'], ['id'])

    with op.batch_alter_table('cf_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cf_table_company_cik_companies_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cf_table_company_cik_companies_table', 'companies_table', ['company_cik'], ['id'])

    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bs_table_company_cik_companies_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bs_table_company_cik_companies_table', 'companies_table', ['company_cik'], ['id'])

    op.drop_table('keyword_types')
    # ### end Alembic commands ###
