"""owner_org

Revision ID: 3f07f4144a65
Revises: e33d07b89c6f
Create Date: 2024-10-24 04:38:41.815791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f07f4144a65'
down_revision = 'e33d07b89c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_keywords_table')
    # with op.batch_alter_table('companies_table', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('owner_org', sa.String(), nullable=True))

    # with op.batch_alter_table('keywords_table', schema=None) as batch_op:
    #     # batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
    #     batch_op.create_foreign_key(batch_op.f('fk_keywords_table_type_id_keyword_types'), 'keyword_types', ['type_id'], ['id'])

    # # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keywords_table_type_id_keyword_types'), type_='foreignkey')
        batch_op.drop_column('type_id')

    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.drop_column('owner_org')

    op.create_table('_alembic_tmp_keywords_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('t', sa.VARCHAR(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['keyword_types.id'], name='fk_keywords_table_type_id_keyword_types'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
