"""keyword type_id foreign key fixed

Revision ID: cfe1c1e1d689
Revises: 3f07f4144a65
Create Date: 2024-10-24 04:45:57.719153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe1c1e1d689'
down_revision = '3f07f4144a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_keywords_table')
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_keywords_table_type_id_keyword_types'), 'keyword_types', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keywords_table_type_id_keyword_types'), type_='foreignkey')
        batch_op.drop_column('type_id')

    op.create_table('_alembic_tmp_keywords_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('t', sa.VARCHAR(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['keyword_types.id'], name='fk_keywords_table_type_id_keyword_types'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
