"""sic

Revision ID: e33d07b89c6f
Revises: 33174ec74397
Create Date: 2024-10-24 01:54:31.145806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33d07b89c6f'
down_revision = '33174ec74397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('companies_table', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('sic_id', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('sic_title', sa.String(), nullable=True))

    # with op.batch_alter_table('keywords_table', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
    #     batch_op.create_foreign_key(batch_op.f('fk_keywords_table_type_id_keyword_types'), 'keyword_types', ['type_id'], ['id'])

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keywords_table_type_id_keyword_types'), type_='foreignkey')
        batch_op.drop_column('type_id')

    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.drop_column('sic_title')
        batch_op.drop_column('sic_id')

    # ### end Alembic commands ###
